# Generated by Django 3.0.5 on 2020-04-09 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.IntegerField(default=0)),
                ('card_id_ans', models.IntegerField(default=0)),
                ('pile_id', models.IntegerField(default=0)),
                ('datestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer', models.CharField(default='X', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='back',
        ),
        migrations.RemoveField(
            model_name='card',
            name='front',
        ),
        migrations.AddField(
            model_name='card',
            name='card_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='card',
            name='first_lng',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='card',
            name='last_good_ans',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='card',
            name='pile_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='second_lng',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
