# Generated by Django 3.0.5 on 2020-05-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0002_auto_20200409_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('user_name', models.CharField(default='NA', max_length=100)),
                ('user_login', models.CharField(default='NA', max_length=100)),
                ('user_password', models.CharField(default='NA', max_length=100)),
                ('user_mail', models.CharField(default='NA', max_length=100)),
                ('new_left_today', models.IntegerField(default=0)),
                ('normal_left_today', models.IntegerField(default=0)),
                ('wrong_left_today', models.IntegerField(default=0)),
            ],
        ),
    ]
