# Generated by Django 3.0.5 on 2020-05-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pile_id', models.IntegerField(default=0)),
                ('pile_name', models.CharField(default='NA', max_length=100)),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
