# Generated by Django 3.0.5 on 2020-05-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0004_pile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pile',
            name='new_left_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pile',
            name='new_per_day',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='pile',
            name='normal_left_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pile',
            name='wrong_left_today',
            field=models.IntegerField(default=0),
        ),
    ]
