# Generated by Django 3.0.5 on 2020-05-15 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0005_auto_20200515_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='next_learn_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
