# Generated by Django 3.0.5 on 2020-05-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0006_card_next_learn_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AppUser',
        ),
    ]
