# Generated by Django 3.0.8 on 2020-07-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0007_auto_20200527_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(max_length=20),
        ),
    ]
